[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Zlib",
]
exceptions = [
  { name = "terminfo", allow = ["WTFPL"] },
  { name = "webpki-root-certs", allow = ["CDLA-Permissive-2.0"] },
  { name = "webpki-roots", allow = ["CDLA-Permissive-2.0"] },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
